### ISSUE TITLE
Possible homing position using a micro switch

### ISSUE THREAD

**Issue by johnmholmes** [dsoze1138/16F676_Frameworks#1]
Hi 
Love the code and started to experiment with it to get a full understanding of what is happening. This will do some great animation on my model railway layout. One question would it be possible to add a homing sequence at start up to pick up one of the spare pins being grounded.

So if the pin if say PIN RA3 is LOW do nothing if PIN RA3 is HIGH run clockwise until the RA3 pin goes LOW.

Also I think there may be an error in the  line of code.

"TRISC = 0xF0;       /* Set PORTC RC0,RC1,RC2,RC3 as outputs */"

00xF0 is 11110000 as we do not need to set bits 6 and 7 

Should this be TRISC = 0x30;  110000

The TRISC does not effect the code running in any way.

Regards
 John

**Comment by dsoze1138** [comment]
I have added a step one revolution or home switch closed function to the code.

TRISC bits 6,7 are "unimplemented" in the PIC16F676 and always read as "0", writing a "1" to "unimplemented" bits has no affect.

**Comment by johnmholmes** [comment]
Thanks for adding the homing to the code.

The hex in TRISC I realised it had no effect but just wanted to check with you.

Cheers
John
