### ISSUE TITLE
lines 90 to 94 possible change required

### ISSUE THREAD

**Issue by johnmholmes** [dsoze1138/16F676_Frameworks#3]
Hi Dan
in lines 90 to 94 in the code table I think the GND should read 5V.

If you take a look at this page 
http://eeshop.unl.edu/pdf/Stepper+Driver.pdf

this is from the university of Nebraska and I had used this in the past for the Arduino side of things.

See what you think.

**Comment by dsoze1138** [comment]
Hi John,
The table in the code from lines 85 to 95 describes the state of the stepper motor wire after the ULN2003 driver board.

The 28BYJ-48 stepper motor uses a "split phase" coil wiring so a simple unipolar drive circuit can be used. Stepper motors with single phase coil wiring require a more complex H-bridge drive circuit. You will find these types of motors used for high torque applications like CNC machine tools.

The information from link you cite is not good. The motor wiring diagram is incomplete as it does not show the common tap between the phases.

This link show a much better description:
https://lastminuteengineers.com/28byj48-stepper-motor-arduino-tutorial/

I know this site has a metric crap ton of adds but is worthwhile as the information is complete and correct.

**Comment by dsoze1138** [comment]
This issue seems resolved to me.

**Comment by johnmholmes** [comment]
Hi Dan
What I was thinking was those wires would not be ground but 5 volts as you can see in the Arduino pin state on the Nebraska site. I have seen the other  version somewhere which I think is possibly wrong. 

Not to worry

**Comment by johnmholmes** [comment]
Check out this page 

https://www.researchgate.net/figure/Stepping-Sequence-of-Half-Drive_tbl3_309127426

you are correct about the split core.

**Comment by johnmholmes** [comment]
Hi Dan
I think I now understand what you are saying at the motor end due to the split coils and the centre tap of 5 volts that coil is grounded. I was think along the lines at the PIC end we are setting the pin for sending to  the ULN2003 and this is possibly  inverting this to GND. 

So in the array we set bit 0 as 1 so 5 volt logic and we have RC0 connected to IN1 on the ULN2003 driver board

So the table is showing the correct value for the stepper motor and not what the PIC is doing.
