### ISSUE TITLE
Line 51 ADCON1 0x10

### ISSUE THREAD

**Issue by johnmholmes** [dsoze1138/16F676_Frameworks#4]
HI Dan
looking at the data sheet for line 51 ADCON1 0x10 in the text you say "set FOSC/8 as ADC clock source".

Should this read as 0x16 instead.

My thinking is bits 0-3 will be read as 0000 and not 1010 as they are unimplemented.

plus to set FOSC/8 clock source we would need to set bits 4 to 6 as 001 so the full register would be 00010000 hence 0x16

Sorry if this seems nit picking

![Screenshot 2023-03-18 160505](https://user-images.githubusercontent.com/60571002/226117518-03ffa7b7-8717-4c9d-9deb-abd7f8e2301c.png)

also line 52 54 &55 could they not be reduced to be one line so 

line 52 would read 0x83 instead of 0x80?

John

**Comment by dsoze1138** [comment]
John,

I suspect that you are doing conversions from binary to decimal then representing that decimal value using hexadecimal syntax.

To set the ADC conversion clock to FOSC/8 the ADCON1 register must have bit 4 set to one and all other bits set to zero. In the C language this has the binary syntax of 0b00010000, hexadecimal syntax of 0x10, decimal syntax of 16.

As to lines 52, 54 & 55, the answer is yes what you propose does work but my preference is to first initialize a function of the controller in the "off" state, set the default configuration, then turn it "on".  Line 54 turns the ADC on, line 55 start a conversion of the voltage present at the RA0/AN0 pin. This is the way I like to initialize the controller ADC, in this specific case it's neither right or wrong but a matter of style.

**Comment by johnmholmes** [comment]
Sorry Dan you are correct again I had forgot to covert the decimal back to HEX another valuable lesson learnt.

The other changes I can see you are correct it makes sense to do it how you have and learning good style from the beginning.

Thank you for the explanation.
